name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Bot
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd ~/projects/FramedataBot &&
            git pull &&
            export TOKEN=${{ secrets.TOKEN }} &&
            export CLIENT_ID=${{ secrets.CLIENT_ID }} &&
            export OWNER_ID=${{ secrets.OWNER_ID }} &&
            export BASE_API_URL=${{ secrets.BASE_API_URL }} &&
            sudo docker-compose -f docker-compose.yml down &&
            sudo docker-compose -f docker-compose.yml up --build -d
          "
